---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I have always struggled with data visualizations. Of course, graphically representing data is vital for communicating findings, however, most of my economics classes (which are mostly econometrics) have focused on regressions and tables of coefficients from data. At the beginning of the quarter, I had a hard time picking between bar charts, boxplots, histograms, and scatterplots. I found that not only did my visualizations need to meet the minimum requirements of being readable and visually interesting, but they had to effectively communicate the right data. Picking the right visualization has been a skill I've worked on in most of my labs and practice activities, but especially in my lab 4 assignment. I received a "G" on problem 6 because the visualization I chose, a bar chart, was confusing for the data it was representing, which were the means of a few categorical variables, not their counts. Through my revision of this problem, I realized that even though a bar chart could show what the means are, they could not communicate what was important about the data: the distribution. It took some extra work to use the data in a boxplot, but it was worth it. Since lab 4, I've taken the critique seriously. In my lab 5 assignment I used the proper visualizations, lines and scatterplots, to show my data in the most readible way.
