---
title: "The Power of Efficiency"
format: html
editor: visual
---

In data science, efficiency is using the least amount of lines, function calls, or packages necessary to wrangle data effectively. While most tasks in data science can be completed in a whole host of ways, efficient approaches are clean, readable, and don't compute more operations or load more data than is needed. Efficient R code makes knitting or rendering files faster and makes the code easier for others to understand or collaborate on. Before this class, I had never learned R formally. Because of that, every time I didn't know how to solve a problem, I would look it up online and find some random R package that included a function that just might work for my application. This meant I was loading 10 different packages into my document that were not meant to be used together, and I rarely went the extra mile to find more efficient functions or functions that could handle more of the criteria I needed to.In this class, however, I've learned so many techniques to make my code more efficient. In Lab 3, I discovered that I could use a "#\|" operator to suppress all of the warnings and messages associated with loading packages for the whole chunk, and no longer had to use the suppressMessages function for every line.

In Lab 3, I learned how to use the across() function (Q7), which saved me from having to write out the same computation for several columns.

In Lab 4 Q3 & Q5, I learned how to use semi_join and anti_join to subset rows, instead of using %in% with a long list of values.

\
